# Generated by Django 4.1.5 on 2023-04-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('owner', models.CharField(max_length=99)),
                ('private', models.BooleanField()),
                ('token', models.CharField(blank=True, max_length=256)),
            ],
        ),
    ]
