# Generated by Django 4.1.5 on 2023-04-07 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_commit_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='deadline',
        ),
    ]
