# Generated by Django 4.1.5 on 2023-04-19 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_remove_commit_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='commits',
            field=models.ManyToManyField(blank=True, related_name='branches', to='submissions.commit'),
        ),
        migrations.CreateModel(
            name='Pull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pulls', to='submissions.repo')),
            ],
        ),
    ]
