# Generated by Django 4.1.5 on 2023-04-19 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_alter_branch_commits_pull'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pull',
            old_name='count',
            new_name='quantity',
        ),
    ]
